# Generated by Django 5.0 on 2023-12-29 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('purpose', models.CharField(max_length=255)),
                ('time_on_task', models.IntegerField(default=0)),
            ],
        ),
    ]
