# Generated by Django 5.0 on 2023-12-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
