# Generated by Django 5.0 on 2023-12-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='counter',
        ),
        migrations.AlterField(
            model_name='entry',
            name='purpose',
            field=models.CharField(default='Debug', max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time_on_task',
            field=models.IntegerField(default=1),
        ),
    ]
